### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by scottbasgaard** [uglyoldbob/rustlin-server#2]
@uglyoldbob stupid question but where can I grab `resources=/home/toughbook/Lineage`?

**Comment by uglyoldbob** [comment]
I'll put up a download link soon

**Comment by scottbasgaard** [comment]
Perfect, thanks!

**Comment by uglyoldbob** [comment]
https://uglyoldbob.com/download/rustlin-server.zip

**Comment by scottbasgaard** [comment]
Thanks!
